CREATE OR REPLACE TYPE tScript IS OBJECT (
    linea VARCHAR2(1000),
    CONSTRUCTOR FUNCTION tScript RETURN SELF AS RESULT,
    MEMBER PROCEDURE Output (SELF IN OUT NOCOPY tScript)
   );

CREATE OR REPLACE TYPE BODY tScript AS
    
   CONSTRUCTOR FUNCTION tScript
      RETURN SELF AS RESULT AS
   BEGIN
      RETURN;
   END;
   MEMBER PROCEDURE Output (SELF IN OUT NOCOPY tScript) IS
   BEGIN
        dbms_output.put_line(SELF.linea);
   END;
END;
   
CREATE OR REPLACE TYPE tScripts IS TABLE OF tScript;